services:
  - type: web
    name: wu-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python confession_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: wu-bot
          property: url
